export const ASSETS = {
  logo: "/assets/logo_jungle_gaming.svg",
  ships: {
    player: "/assets/png/default/ships/ship_1.png",
    chaser: "/assets/png/default/ships/ship_2.png",
    shooter: "/assets/png/default/ships/ship_5.png",
  },
  projectile: "/assets/png/default/ship_parts/cannon_ball.png",
  tiles: {
    water: "/assets/png/default/tiles/tile_73.png",
    island: "/assets/png/default/tiles/tile_23.png",
    island2: "/assets/png/default/tiles/tile_6.png",
    island3: "/assets/png/default/tiles/tile_7.png",
    island4: "/assets/png/default/tiles/tile_8.png",
    island5: "/assets/png/default/tiles/tile_9.png",
    island6: "/assets/png/default/tiles/tile_24.png",
    island7: "/assets/png/default/tiles/tile_39.png",
    island8: "/assets/png/default/tiles/tile_40.png",
  },
  effects: {
    explosion1: "/assets/png/default/effects/explosion_1.png",
    explosion2: "/assets/png/default/effects/explosion_2.png",
    explosion3: "/assets/png/default/effects/explosion_3.png",
  },
  ui: {
    atlas: "/assets/spritesheet/ui_sheet.json",
    title: "/assets/png/default/ui/menu/title_pirate_battle.png",
    panel: "/assets/png/default/ui/menu/panel_menu.png",
    primary: "/assets/png/default/ui/menu/button_primary_normal.png",
    primaryPressed: "/assets/png/default/ui/menu/button_primary_pressed.png",
    secondary: "/assets/png/default/ui/menu/button_secondary_normal.png",
    heart: "/assets/png/default/ui/hud/icon_heart.png",
    score: "/assets/png/default/ui/hud/icon_score.png",
    time: "/assets/png/default/ui/hud/icon_time.png",
    healthFrame: "/assets/png/default/ui/hud/health_frame.png",
    healthGreen: "/assets/png/default/ui/hud/health_fill_green.png",
    healthAmber: "/assets/png/default/ui/hud/health_fill_amber.png",
    healthRed: "/assets/png/default/ui/hud/health_fill_red.png",
    enemyHealthFrame: "/assets/png/default/ui/hud/enemy_health_frame.png",
    enemyHealthGreen: "/assets/png/default/ui/hud/enemy_health_fill_green.png",
    enemyHealthRed: "/assets/png/default/ui/hud/enemy_health_fill_red.png",
    iconPause: "/assets/png/default/ui/controls/icon_pause.png",
    iconClose: "/assets/png/default/ui/controls/icon_close.png",
    iconPlay: "/assets/png/default/ui/controls/icon_play.png",
    iconForward: "/assets/png/default/ui/controls/icon_forward.png",
    iconLeft: "/assets/png/default/ui/controls/icon_turn_left.png",
    iconRight: "/assets/png/default/ui/controls/icon_turn_right.png",
    iconFireFront: "/assets/png/default/ui/controls/icon_fire_front.png",
    iconFireLeft: "/assets/png/default/ui/controls/icon_fire_left.png",
    iconFireRight: "/assets/png/default/ui/controls/icon_fire_right.png",
  },
  sounds: {
    cannon: "/assets/sounds/cannon_fire_1.wav",
    enemyCannon: "/assets/sounds/cannon_fire_2.wav",
    broadside: "/assets/sounds/cannon_broadside.wav",
    hit: "/assets/sounds/ship_wood_hit_1.wav",
    playerHit: "/assets/sounds/ship_wood_hit_2.wav",
    splash: "/assets/sounds/cannonball_water_hit_1.wav",
    explosion: "/assets/sounds/ship_explosion_1.wav",
    score: "/assets/sounds/score_point.wav",
    healthLow: "/assets/sounds/health_low.wav",
    timeWarning: "/assets/sounds/time_warning.wav",
    complete: "/assets/sounds/game_complete.wav",
    ambience: "/assets/sounds/ocean_ambience_loop.wav",
    start: "/assets/sounds/game_start.wav",
    pause: "/assets/sounds/game_pause.wav",
    resume: "/assets/sounds/game_resume.wav",
    gameOver: "/assets/sounds/game_over.wav",
  },
} as const;

export const REQUIRED_ASSETS = [
  ASSETS.logo,
  ...Object.values(ASSETS.ships),
  ASSETS.projectile,
  ...Object.values(ASSETS.tiles),
  ...Object.values(ASSETS.effects),
  ASSETS.ui.atlas,
  ...Object.values(ASSETS.sounds),
];

/** Caminho de um tile do tileset (`tile_N.png`, 64×64). */
export const tileUrl = (n: number) => `/assets/png/default/tiles/tile_${n}.png`;
